//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.TabPort.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.TabPort.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favicon Db Path.
        /// </summary>
        internal static string custom_favicon_db_path {
            get {
                return ResourceManager.GetString("custom_favicon_db_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Favicon database location. Defaults to Chromium layout. For Firefox layout, please select Firefox in &quot;Favicon Db Priority&quot; below..
        /// </summary>
        internal static string custom_favicon_db_path_description {
            get {
                return ResourceManager.GetString("custom_favicon_db_path_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string custom_port {
            get {
                return ResourceManager.GetString("custom_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open WebSocket Server on the custom port  .
        /// </summary>
        internal static string custom_port_description {
            get {
                return ResourceManager.GetString("custom_port_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favicon Db Priority.
        /// </summary>
        internal static string favicon_db_path_priority {
            get {
                return ResourceManager.GetString("favicon_db_path_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the priority for Favicon database retrieval..
        /// </summary>
        internal static string favicon_db_path_priority_description {
            get {
                return ResourceManager.GetString("favicon_db_path_priority_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website icon display will be temporarily disabled until reset..
        /// </summary>
        internal static string open_connection_sqlite_exception_toast_description {
            get {
                return ResourceManager.GetString("open_connection_sqlite_exception_toast_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TabPort] Error opening database connection..
        /// </summary>
        internal static string open_connection_sqlite_exception_toast_title {
            get {
                return ResourceManager.GetString("open_connection_sqlite_exception_toast_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between open browser tabs..
        /// </summary>
        internal static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabPort.
        /// </summary>
        internal static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Weight.
        /// </summary>
        internal static string title_weight {
            get {
                return ResourceManager.GetString("title_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weight of the website title in searches..
        /// </summary>
        internal static string title_weight_description {
            get {
                return ResourceManager.GetString("title_weight_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Weight.
        /// </summary>
        internal static string url_weight {
            get {
                return ResourceManager.GetString("url_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weight of the website URL in searches..
        /// </summary>
        internal static string url_weight_description {
            get {
                return ResourceManager.GetString("url_weight_description", resourceCulture);
            }
        }
    }
}
